### ISSUE TITLE
Question: manufacturing process

### ISSUE THREAD

**Issue by mahrud** [myriadrf/RASDR#6]
Open hardware files are provided, but I'm not sure what sort of facility I should be looking for to actually create them and how much it would cost. Would a big university have the equipment to manufacture this?

**Comment by bvacaliuc** [comment]
We provided a complete workup on manufacturing cost and presented it at the [2015 SARA annual conference](http://radio-astronomy.org/?q=node/208).

See this [spreadsheet](https://github.com/myriadrf/RASDR/blob/master/manufacture/rasdr2-bom-and-components.xlsx) for details.  We worked up quantity of 10, 25 and 100 units.  The spreadsheet contains part numbers and quotation numbers from our suppliers, [Advanced Assembly](http://aa-pcbassembly.com/) and [Protocase, Inc.](http://www.protocase.com/).

Our intent was to provide complete manufacturing documentation for turnkey production.  "Just add $$$...".  There is still some work to be done in assembling the components in the case, but that can be accomplished by eager (under)graduate students.  :)
